// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0AfPoRqqKA14EhebyezN86573YxDw2-w',
    appId: '1:224930247264:web:b10f4ea90e237a00764905',
    messagingSenderId: '224930247264',
    projectId: 'no-mark-backend',
    authDomain: 'no-mark-backend.firebaseapp.com',
    storageBucket: 'no-mark-backend.appspot.com',
    measurementId: 'G-RDXFXH1BS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62FEClP6PTB0-lG60pdcS6q_QJUvVxJk',
    appId: '1:224930247264:android:bcc5cbbb8fa2231d764905',
    messagingSenderId: '224930247264',
    projectId: 'no-mark-backend',
    storageBucket: 'no-mark-backend.appspot.com',
  );
}
